CREATE DATABASE sql7391703 CHARACTER SET utf8mb4;

USE sql7391703;

CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT(2) NOT NULL,
NOMBRE VARCHAR(10) NOT NULL,
FECHA_DE_ALTA DATE NOT NULL,
ID_CLIENTE INT(2) NOT NULL,
PRIMARY KEY (ID_PROVEEDOR));


INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, FECHA_DE_ALTA, ID_CLIENTE) VALUES ('1', 'COCA-COLA', '2021-02-08', '5'); 
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, FECHA_DE_ALTA, ID_CLIENTE) VALUES ('2', 'PEPSI', '2021-02-09', '5');
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, FECHA_DE_ALTA, ID_CLIENTE) VALUES ('3', 'REDBULL', '2021-02-10', '6');

COMMIT;
